name: Resuable workflow
on:
  workflow_call:
    inputs:
      message:
        description: "Message to print"
        required: false
        type: string
        default: "This is a reusable workflow!"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output Message
        run: echo "${{ inputs.message }}"
