name: Use resuable workflow
on: push
jobs:
  call_reusable_workflow:
    uses: ./.github/workflows/resuable.yml
    with:
      message: "Hello from the calling workflow!"
    # secrets:
    #   EXAMPLE_SECRET: ${{ secrets.EXAMPLE_SECRET }}
  print_output:
    runs-on: ubuntu-latest
    needs: call_reusable_workflow
    steps:
      - name: Print Reusable Workflow Output
        run: |
          echo "Reusable Workflow Output: ${{ needs.call_reusable_workflow.outputs.example_output }}"
